# Generated by Django 5.1.3 on 2024-11-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ENABLE', 'ENABLE'), ('DISABLE', 'DISABLE')], max_length=25)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
