# Generated by Django 5.1.3 on 2024-11-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUserTableData',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.useraccounttabledata')),
            ],
            options={
                'db_table': 'employee_user',
            },
            bases=('account.useraccounttabledata',),
        ),
        migrations.CreateModel(
            name='RoleTableData',
            fields=[
                ('role', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserRoleTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_user.employeeusertabledata')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_user.roletabledata')),
            ],
            options={
                'db_table': 'user_role',
                'constraints': [models.UniqueConstraint(fields=('employee', 'role'), name='unique_employee_role')],
            },
        ),
    ]
