# Generated by Django 5.1.3 on 2024-11-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUserTableData',
            fields=[
                ('birthdate', models.DateField()),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.useraccounttabledata')),
            ],
            options={
                'db_table': 'client_user',
            },
            bases=('account.useraccounttabledata',),
        ),
    ]
