# Generated by Django 5.1.3 on 2024-12-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTableData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=250)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserAccountTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ENABLE', 'ENABLE'), ('DISABLE', 'DISABLE')], max_length=25)),
                ('birthdate', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='UserRoleTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccounttabledata')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.roletabledata')),
            ],
            options={
                'db_table': 'user_role',
                'constraints': [models.UniqueConstraint(fields=('employee', 'role'), name='unique_employee_role')],
            },
        ),
    ]
